export const stories: {[key: string]: string[]} = {
  arts: [
    "Stories involving consent and violence are important for some preteens to read, writers say, but a sensitive approach and a light touch are key.",
    "In a series of videos, the choreographer Alonzo King instructs performers to play with the natural world. \"Let's use the wind instead of ignoring it.”",
    "Many Americans reflexively believe that good fortune is always around the corner. But ignoring the dark potential of life can have dire consequences.",
    "In her new HBO documentary, “Bully. Coward. Victim. The Story of Roy Cohn,” the director Ivy Meeropol pushes past the easy labels in search of the human being.",
    "The rapid rise of Bookshop.org during the shutdown has been hailed as a boon for independent stores. But some booksellers worry it could become another competitor for online business.",
    "Reopening may be a long way off, but bar regulars have reassembled outdoors, and owners are trying to balance business and safety.",
    "Researchers in Japan have developed a soap bubble-based pollination method that is as effective as doing it by hand.",
    "Cities are accelerating applications and waiving fees to allow alfresco dining, but the moves are disrupting neighborhoods and cutting much-needed tax revenue.",
    "Distilleries, cooking schools, wineries and food halls from California to South Minneapolis are adjusting to social distancing and hygiene in a new era of travel.",
    "Suppliers and restaurants are scrambling after an outbreak in Beijing triggered fears that salmon may have spread it. Officials later absolved the fish of blame, but consumers are avoiding it anyway.",
  ],
  innovation: [
    "Now that the stock market has largely shrugged off the coronavirus, start-ups are scrambling to go public.",
    "Apple has repeatedly denied Facebook’s new Gaming app from appearing in its App Store, citing its own rules.",
    "Using native plant species helps, but there are two other things you can do to make birds feel at home — and they don’t involve any planting at all.",
    "Fifty years after the first Pride March, the authors Jericho Brown, Carmen Maria Machado and Thomas Page McBee reflect on a complicated moment for the L.G.B.T.Q. community.",
    "Fortnite Chapter 2 Season 3 is here and with it a ton of updates, big (the hunting rifle is back!) and small (headshot damage has been nerfed a touch).",
    "A newly discovered spyware effort has attacked users through 32 million downloads of extensions to Google’s market-leading Chrome web browser.",
    "If three new Pokemon games (including Pokemon Snap) and a brand new piece of DLC wasn’t enough for you, The Pokemon Company closed its Pokemon Presents presentation with the announcement that another Pokemon Presents presentation will be happening on June 24th focusing on a larger title.",
    "The prevailing wisdom within Sony is that exclusive games sell consoles. And if you were wondering — or maybe hoping — if that attitude might change with the PS5, one of the company’s executive vice presidents is doubling down on the power of an exclusive.",
    "Twitter has added another enhancement to its social network. Users on iOS are now able to add voice messages to their tweets which will complement the short text-based message.",
    "The oversized kidney grille on BMW's new-generation 4 Series has been a talking point since its debut, but the design boss has assured its detractors it won't be making it onto other models in the range.",
  ],
  business: [
    "COVID jitters set the Australian sharemarket up for early losses and a dour jobs report weighed it down further as investors recoiled at economic damage wrought by coronavirus lockdowns.",
    "The Zip Co Ltd (ASX: Z1P) share price has soared 64.5% in June. The company is undergoing a $200 million capital raising to acquire United States-based buy now, pay later (BNPL) provider, QuadPay. But is the Zip Co share price getting too expensive? ",
    "Earlier today the Afterpay Ltd (ASX: APT) share price continued its meteoric rise and stormed higher again. The payments company’s shares rose 3% to hit a record high of $59.64.",
    "Amid nationwide protests against racism, major US food companies on Wednesday said they would change the Aunt Jemima and Uncle Ben's brands, both of which feature African American mascots.",
    "New Zealand's gross domestic product suffered its biggest fall since 1991 as the coronavirus pandemic began to bite in the first quarter.",
    "Infigen Energy has urged shareholders to back a “friendly” counter takeover offer from Spanish renewables giant Iberdrola, that values the Australian wind energy firm at around $835 million and trumps an earlier hostile offer.",
    "Ardent Leisure says a class action has been served against it in regards to the Dreamworld tragedy that resulted in the death of four people.",
    "The Splitit Ltd (ASX: SPT) share price is on the rise today after the buy now, pay later (BNPL) provider announced a partnership with Mastercard. The multi-year agreement is intended to accelerate the global adoption of Splitit’s instalment solution. ",
    'Reserve Bank economists considered urging the Federal Government to shut down the real estate industry, "pausing" sales of established homes to avoid perceptions of a coronavirus-inspired housing market crash.',
    "Energy titan Trevor St Baker says the world's most polluting cars will end up in Australia if the government does not act to set vehicle emissions targets.",
  ],
  world: [
    "The former national security adviser John Bolton’s book says the House should have looked at potentially impeachable acts beyond Ukraine.",
    "Mr. Bolton adds a striking new allegation by saying President Trump overtly linked trade negotiations with China to his own re-election prospects.",
    "Instead of offering President Trump a glide path back into the campaign season, Saturday’s rally in Tulsa has become yet another flash point for a candidate who has repeatedly displayed insensitivity about race.",
    "Advisers and allies say the president’s repeated acts of self-destruction have significantly damaged his re-election prospects, and yet he appears mostly unable, or unwilling, to curtail them.",
    "As state and local governments confront a new wave of coronavirus infections, President Trump is sending mixed messages and Washington’s public health bully pulpit has gone silent.",
    "As more Republicans say they support at least some L.G.B.T.Q. protections, President Trump and party leaders continue to stand in opposition and particularly target transgender Americans.",
    "Republicans proposed incentives for state and local police departments to change their tactics as Democrats pushed for a sweeping overhaul.",
    "Kim Yo-jong’s deepening power and “revolutionary” bloodline make her a potential candidate to replace her brother in patriarchal North Korea.",
    "Suppliers and restaurants are scrambling after an outbreak in Beijing triggered fears that salmon may have spread it. Officials later absolved the fish of blame, but consumers are avoiding it anyway.",
    "Xi Jinping and Narendra Modi have sought to project a muscular global profile despite their countries’ problems. Backing down could hurt their efforts.",
  ],
  sports: [
    "No doubles in table tennis. No caddies on the golf course. No sharing snorkels. The N.B.A. sent team personnel a voluminous list of health protocols.",
    "Four games involving historically black colleges and universities were canceled, in part illustrating an economic difficulty for games played at neutral sites.",
    "European soccer officials plan to salvage their biggest competition with a 12-day event in Portugal. But first they have to eliminate four teams.",
    "Golfers went from carping about swab testing to nearly forgetting about social distancing between the ropes, proving a sports truism: Athletes adjust and always keep their eyes on the prize(s).",
    "The plan for a doubleheader of tournaments at the U.S.T.A. Billie Jean King National Tennis Center still needs formal government approval. And it’s unclear how many players will take part.",
    "The Bundesliga’s sequestered competition only involves about one-sixth as many people as the N.B.A.’s planned campus, but it offers a glimpse of what to expect in Florida.",
    "Teams would play 60 games starting in mid-July under a framework Commissioner Rob Manfred said he had reached with Tony Clark, the union head.",
    "Americans are eager to have their favourite sports back. But three months after most leagues shut down, there are only loose plans, good intentions and a nervous hope that it doesn’t go wrong.",
    "British singer-songwriter Dame Vera Lynn, who held a special place in the hearts of Britons for boosting morale during World War II, has died aged 103, her family says.",
    "Standing on stage in front of the royals would be nerve-racking for most people but for Hollywood star Rebel Wilson, it was the chance to have some fun.",
  ],
  quotes: [
    "A member of a house share in London has claimed that they discovered their letting agent had secretly been living in their house for two days.",
    "Sofia Lips, from Lancashire, funds her plastic surgery by posing for saucy photos online and by carrying out men's unusual requests",
    "A woman who found out her husband had been moaning that she had forgotten to cut his sandwiches into triangles took revenge to ensure he won't be complaining again.",
    "A five-bedroom house has attracted more interested buyers in one, four-day open home than an estate agent has seen in 25 years of his career, with people queuing for houses to view it.",
    'Sharing the funny story Mumsnet, she explained: "I wanted as many people to see this as possible - it is a salient warning to check your children\'s work before sending it back into school....." and added a laughing emoji for good measure.',
    "Bizarre footage shows the moment two apparent ghosts work out at an outdoor gym, leaving police officers baffled.",
    "A woman exercising at the beach has been slammed online for being 'disrespectful' and for having \"bad manners.\"",
    "Prince Harry gave up a lot when he packed his bags and waved goodbye to the UK - leaving his royal title behind him - in favour of a new life in LA.",
    "With McDonald's recently re-opening a number of their drive-thrus for takeaway, people all over have been queuing for a Big Mac, fries, some McNuggets and a McFlurry.",
  ],
};
